config/routes.rb
Rails.application.routes.draw do
  resources :cats, only: [:index, :show, :new, :create, :update, :edit]

  resources :cat_rental_requests, only: [:index, :new, :create]
end

app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :integer          not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Cat < ActiveRecord::Base
  validates :birth_date, :color, :name, :sex, presence: true
  validates :color, inclusion: { in: %w(black white grey calico),
    message: "%{value} is not a valid color" }
  validates :sex, inclusion: { in: %w(M F),
    message: "%{value} is not a valid sex" }

  has_many :cat_rental_requests,
    dependent: :destroy


  def age
    now = Date.today
    now.year - birth_date.year - (past_birthday?(now) ? 0 : 1)
  end

  private
  def past_birthday?(date)
    (date.month > birth_date.month || (date.month == birth_date.month && date.day >= birth_date.day))
  end
end

app/models/cat_rental_request.rb
# == Schema Information
#
# Table name: cat_rental_requests
#
#  id         :integer          not null, primary key
#  cat_id     :integer          not null
#  start_date :date             not null
#  end_date   :date             not null
#  status     :string           default("PENDING"), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class CatRentalRequest < ActiveRecord::Base
  validates :status, inclusion: { in: %w(PENDING APPROVED DENIED)}
  validates :cat_id, :start_date, :end_date, :status, presence: true

  validate :overlapping_approved_requests, :overlapping_pending_requests
  validate :start_before_end

  belongs_to :cat

  def approve!
    self.status = "APPROVED"

  end

  private
  def overlapping_requests
    overlapping_requests1 = CatRentalRequest.where(cat_id: self.cat_id, start_date: self.start_date..self.end_date).where.not(id: self.id)
    #.or(cat_id: self.cat_id, end_date: self.start_date..self.end_date)
     overlapping_requests2 = CatRentalRequest.where(cat_id: self.cat_id, end_date: self.start_date..self.end_date).where.not(id: self.id)

     overlapping_requests = (overlapping_requests1 + overlapping_requests2)

    overlapping_requests.uniq
  end

  def overlapping_approved_requests
    if overlapping_requests.select{ |request| request[:status] == "APPROVED" } != []
      self.errors[:request]<< "overlaps an approved request"
    end
  end

  def overlapping_pending_requests
    if overlapping_requests.select { |request| request[:status] == "PENDING" } != []
      self.errors[:request]<< "overlaps a pending request"
    end
  end

  def start_before_end
    if self.end_date < self.start_date
      self.errors[:start] << "must be before end"
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  def index
    @cat_rental_requests = CatRentalRequest.all
    render :index
  end

  def show
    @cat_rental_request = CatRentalRequest.find_by_id(params[:id])
    render :show
  end

  def new
    @cat_rental_request = CatRentalRequest.new
    render :new
  end

  def create
    @cat_rental_request = CatRentalRequest.new(cat_rental_request_params)
    if @cat_rental_request.save
      redirect_to cat_url(Cat.find_by_id(cat_rental_request_params[:cat_id]))
    else
      render :new
    end
  end

  def update
    @cat_rental_request = CatRentalRequest.find(params[:id])
    if @cat_rental_request.update(cat_rental_request_params)
      redirect_to cat_url(@cat_rental_request)
    else
      render :edit
    end
  end

  def edit
    @cat_rental_request = CatRentalRequest.find(params[:id])
    render :edit
  end

  private
  def cat_rental_request_params
    params.require(:cat_rental_request).permit(:cat_id, :start_date, :end_date, :status)
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find_by_id(params[:id])
    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to cat_url(@cat)
    else
      render :new
    end
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      render :edit
    end
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  private
  def cat_params
    params.require(:cat).permit(:name, :birth_date, :color, :sex, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cat_rental_requests/_form.html.erb
<% if cat_rental_request.persisted? %>
  <% action_url = cat_rental_request_url(cat_rental_request)%>
  <% method = "PATCH" %>
  <% button_val = "Update Cat" %>
<% else %>
  <% action_url = cat_rental_requests_url %>
  <% method = "POST" %>
  <% button_val = "Request Rental" %>
<% end %>

<form action="<%= action_url %>" method="post">


  <input type="hidden" name="_method" value="<%= method %>">

  <label for="Choose a Cat">Choose a Cat</label>
  <select id="Choose a Cat" name="cat_rental_request[cat_id]">
    <option value="Select Cat" disabled="true" <%= @cat_rental_request.cat_id ? "" : "selected"%> >Select Cat</option>
      <% Cat.all.each do |cat|%>
        <option value=" <%= cat.id %>" > <%= cat.name %> </option>
    <% end %>
  </select>

  <br>

  <label for="Start_date">Start Date</label>
  <input id="Start_date" type="date" name="cat_rental_request[start_date]" value="<%= @cat_rental_request.start_date %>">

  <br>

  <label for="End_date">End Date</label>
  <input id="End_date" type="date" name="cat_rental_request[end_date]" value="<%= @cat_rental_request.end_date %>">

  <br>

  <input type="submit" value="<%= button_val %>">

</form>

app/views/cat_rental_requests/index.html.erb
<h1>All the Cats</h1>

<ul>
  <% @cat_rental_requests.each do |request| %>
   <a href = "/cat_rental_requests/<%=request.id%>"><%= request.id %></a>
   <br>
 <% end %>
    <!-- <%#= render @cats %> -->
</ul>

app/views/cat_rental_requests/new.html.erb
<h1>Rent a Cat!</h1>

<%= render 'form', cat_rental_request: @cat_rental_request, action: :new %>

app/views/cats/_form.html.erb
<% if cat.persisted? %>
  <% action_url = cat_url(cat)%>
  <% method = "PATCH" %>
  <% button_val = "Update Cat" %>
<% else %>
  <% action_url = cats_url %>
  <% method = "POST" %>
  <% button_val = "Add Cat" %>
<% end %>

<form action="<%= action_url %>" method="post">


  <input type="hidden" name="_method" value="<%= method %>">

  <label for="name">Name</label>
  <input id="name" type="text" name="cat[name]" value="<%= @cat.name %>">

  <br>

  <label for="sex">Sex</label>
  <% if @cat.sex == 'M' %>
    M <input type="radio" name="cat[sex]" value="M" checked = "true">
    F <input type="radio" name="cat[sex]" value="F">
  <% else %>
    M <input type="radio" name="cat[sex]" value="M">
    F <input type="radio" name="cat[sex]" value="F" checked = "true">
  <% end %>

  <br>

  <label for="color">Color</label>
  <select id="color" name="cat[color]">
    <option value="Select Color" disabled="true" <%= @cat.color ? "" : "selected"%> >Select Color</option>
    <option value="grey" <%= @cat.color == 'grey' ? "selected" : "" %> >grey</option>
    <option value="black" <%= @cat.color == 'black' ? "selected" : "" %> >black</option>
    <option value="white" <%= @cat.color == 'white' ? "selected" : "" %> >white</option>
    <option value="calico" <%= @cat.color == 'calico' ? "selected" : "" %> >calico</option>
  </select>

  <br>

  <label for="birth_date">Birthday</label>
  <input id="birth_date" type="date" name="cat[birth_date]" value="<%= @cat.birth_date %>">

  <br>

  <label for="description">Description</label>
    <textarea name="cat[description]">
      <%= @cat.description %>
    </textarea>

  <br>

    <input type="submit" value="<%= button_val %>">

</form>

app/views/cats/edit.html.erb
<h1>Edit a Cat!</h1>

<%= render 'form', cat: @cat, action: :edit %>

app/views/cats/index.html.erb
<h1>All the Cats</h1>

<ul>
  <% @cats.each do |cat| %>
   <a href = "/cats/<%=cat.id%>"><%= cat.name %></a>
   <br>
 <% end %>
    <!-- <%#= render @cats %> -->
</ul>

app/views/cats/new.html.erb
<h1>Add a Cat!</h1>

<%= render 'form', cat: @cat, action: :new %>

app/views/cats/show.html.erb
<h3><%= @cat.name %></h3>
<!-- <ul>
  <li>
    Color: <%#= @cat.color %>
  </li>
  <li>
    Sex: <%#= @cat.sex %>
  </li>
  <li>
    Birthday: <%#= @cat.birth_date %>
  </li>
  <li>
    Age: <%#= @cat.age %>
  </li>
  <li>
    Description: <%#= @cat.description %>
  </li>
</ul> -->

<style>
table, th, td {
    border: 1px solid black;
}
</style>

<table style="width:50%">
  <thead>
    <tr>
      <th>Color</th>
      <th>Sex</th>
      <th>Birthday</th>
      <th>Age</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @cat.color %></td>
      <td><%= @cat.sex %></td>
      <td><%= @cat.birth_date %></td>
      <td><%= @cat.age %></td>
      <td><%= @cat.description %></td>
    </tr>
  </tbody>
</table>

<h4>Rentals</h4>
<table style="width:50%">
  <thead>
    <tr>
      <th>Start Date</th>
      <th>End Date</th>
    </tr>
  </thead>
  <tbody>
    <% @cat.cat_rental_requests.order(:start_date).each do |request| %>
      <tr>
        <td> <%= request.start_date %> </td>
        <td> <%= request.end_date %> </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cats99</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>